The ''7-base_geometry'' module
============================

Using ''BaseGeometry''
---------------------

This is an example text file . First import

''BaseGeometry'' from the ''7-base_geometry'' module:
>>> bs = __import__('7-base_geometry').BaseGeometry()
>>> bs.integer_validator("my int", 1)

>>> bs.integer_validator("my int", "string")
Traceback (most recent call last):
...
TypeError: my int must be an integer
>>> bs.integer_validator(None)
Traceback (most recent call last):
...
TypeError: integer_validator() missing 1 required positional argument: 'value'
>>> bs.integer_validator()
Traceback (most recent call last):
...
TypeError: integer_validator() missing 2 required positional arguments: 'name' and 'value'
>>> bs.integer_validator("sas", -5)
Traceback (most recent call last):
...
ValueError: sas must be greater than 0
>>> bs.integer_validator("sas", 0)
Traceback (most recent call last):
...
ValueError: sas must be greater than 0
>>> bs.integer_validator(None, [5])
Traceback (most recent call last):
...
TypeError: None must be an integer
>>> bs.integer_validator("sas", True)
Traceback (most recent call last):
...
TypeError: sas must be an integer
>>> bs.integer_validator("sas", None)
Traceback (most recent call last):
...
TypeError: sas must be an integer
>>> bs.integer_validator("sas")
Traceback (most recent call last):
...
TypeError: integer_validator() missing 1 required positional argument: 'value'
>>> bs.integer_validator("sas", 100)

>>> bs.integer_validator([5], 43, 49)
Traceback (most recent call last):
...
TypeError: integer_validator() takes 3 positional arguments but 4 were given
>>> bs.integer_validator("sas", (45, 54, 59))
Traceback (most recent call last):
...
TypeError: sas must be an integer
>>> bs.integer_validator("sas", {65, 67, 79})
Traceback (most recent call last):
...
TypeError: sas must be an integer
>>> bs.area(53, 54)
Traceback (most recent call last):
...
TypeError: area() takes 1 positional argument but 3 were given
>>> bs.area()
Traceback (most recent call last):
...
Exception: area() is not implemented
>>> bs.area(87)
Traceback (most recent call last):
...
TypeError: area() takes 1 positional argument but 2 were given
